name:  Civilization
main:  org.macroprod.civilization.Civilization
version: 1.0
depend: [LibsDisguises, ProtocolLib]
commands:
  settler:
    description: Spawns a miner villager
    usage: /<command>
  fuckbob:
    description: test
  fuckkevin:
    description: Fucks klevin
