name:  Civilization
main:  org.macroprod.civilizationion.Civilization
version: 1.0
commands:
  spawnminer:
    description: Spawns a miner villager
    usage: /<command>
  reload:
    description: Reloads the plugin
    usage: /civilization <command>