name:  Civilization
main:  org.macroprod.civilization.Civilization
version: 1.0
depend: [LibsDisguises, ProtocolLib]
commands:
  tp:
    description: controls player teleports
  slave:
    description: Control slaves
    usage: /<command> <instruction> <arguments>
